xgds_map_server/urls.py
#__BEGIN_LICENSE__
# Copyright (c) 2015, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All rights reserved.
#
# The xGDS platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#__END_LICENSE__

from django.conf.urls import url, include  # pylint: disable=W0401

from django.conf import settings
from resumable.views import ResumableUploadView

from xgds_map_server import views

urlpatterns = [url(r'^$', views.getMapServerIndexPage,{},'xgds_map_server_index'),
               url(r'^$', views.getMapServerIndexPage,{},'map'),
               url(r'^feedPage/', views.getGoogleEarthFeedPage,{},'xgds_map_server_feed_page'),
    
               # For copying feature data to the session variables
               url(r'^copyFeatures$', views.copyFeatures, {}, 'copyFeatures'),
    
               # for saving map layer itself
               url(r'^saveMaplayer.json$', views.saveMaplayer, {}, 'saveMaplayer'),
    
               # HTML tree of maps
               url(r'^maptree/', views.getMapTreePage, {},'mapTree'),
               url(r'^setTransparency/(?P<uuid>[\w-]+)/(?P<mapType>\w+)/(?P<value>[\d]+)', views.setTransparency, {}, 'mapSetTransparency'),
    
               # Open Map Editor on a map layer
               url(r'^mapeditor/(?P<layerID>[\w-]+)/', views.getMapEditorPage, {}, 'mapEditLayer'),

               # HTML detail view of map
               url(r'^detail/(?P<mapID>[\w-]+)/', views.getMapDetailPage,{},'mapDetail'),
    
               # HTML detail of a folder (group)
               url(r'^folderDetail/(?P<groupID>[\w-]+)/', views.getFolderDetailPage, {}, 'folderDetail'),
    
               # HTML view to delete a folder (group)
               url(r'^folderDelete/(?P<groupID>[\w-]+)/', views.getDeleteFolderPage, {}, 'folderDelete'),
    
               # HTML view to add a folder (group)
               url(r'^folderAdd/', views.getAddFolderPage, {}, 'folderAdd'),
    
               # HTML view to add new map
               url(r'^addkml/', views.getAddKmlPage, {}, 'addKml'),
               url(r'^addlayer/', views.getAddLayerPage, {}, 'mapAddLayer'),
               url(r'^addGeoJSON/', views.getAddGeoJSONPage, {}, 'mapAddGeoJSON'),
               url(r'^addGeotiff/', views.getAddGeotiffPage, {}, 'mapAddGeotiff'),
               url(r'^editGeotiff/(?P<geotiffID>[\w-]+)/', views.getEditGeotiffPage, {}, 'mapEditGeotiff'),
               url(r'^addLayerFromSelected/', views.addLayerFromSelected, {}, 'addLayerFromSelected'),
               url(r'^addTile/', views.getAddTilePage, {}, 'mapAddTile'),
               url(r'^editTile/(?P<tileID>[\w-]+)/', views.getEditTilePage, {}, 'mapEditTile'),
               url(r'^addMapDataTile/', views.getAddMapDataTilePage, {}, 'mapAddDataTile'),
               url(r'^editMapDataTile/(?P<tileID>[\w-]+)/', views.getEditMapDataTilePage, {}, 'mapEditDataTile'),
               url(r'^addWMS/', views.getAddWMSTilePage, {}, 'mapAddWMSTile'),
               url(r'^editWMS/(?P<tileID>[\w-]+)/', views.getEditWMSTilePage, {}, 'mapEditWMSTile'),

               # TODO all of the below urls depended on xgds_data and need to be reimplemented
               # url(r'^addMapSearch/', views.getAddMapSearchPage, {}, 'mapAddMapSearch'),
               # url(r'^editMapSearch/(?P<mapSearchID>[\w-]+)/', views.getEditMapSearchPage, {}, 'mapEditMapSearch'),
               # url(r'^addMapCollection/', views.getAddMapCollectionPage, {}, 'mapAddMapCollection'),
               # url(r'^editMapCollection/(?P<mapCollectionID>[\w-]+)/', views.getEditMapCollectionPage, {}, 'mapEditMapCollection'),
               # url(r'^doMapSearch/', views.searchWithinMap, {}, 'doMapSearch'),
               # url(r'^saveMapSearch/', views.saveSearchWithinMap, {}, 'saveMapSearch'),

               # HTML view to confirm deletion of view
               url(r'^delete/(?P<nodeID>[\w-]+)/', views.getDeleteNodePage, {}, 'nodeDelete'),
    
               # List of deleted maps that can be un-deleted
               url(r'^deleted/', views.getDeletedNodesPage, {}, 'deletedNodes'),
               
               # JSON-accepting url that moves maps/folders around
               url(r'^moveNode', views.moveNode, {}, 'moveNode'),
               
               # JSON-accepting url that changes visibility for a node
               url(r'^setNodeVisibility', views.setNodeVisibility, {}, 'setNodeVisibility'),

               # By default if you just load the app you should see the list
               url(r'^uploadResumable/$', ResumableUploadView.as_view(), name='uploadResumable'),
               
               url(r'^search/mapBounded/$', views.getMapBoundedSearchPage, {}, 'search_map_bounded_page'),

               url(r'^search/$', views.getSearchPage, {}, 'search_map'),
               url(r'^search/(?P<modelName>[\w]+)$', views.getSearchPage, {}, 'search_map_object'),
               url(r'^search/(?P<modelName>\w+)/(?P<filter>(([\w]+|[a-zA-Z0-9:._\-\s]+),*)+)$', views.getSearchPage, {}, 'search_map_object_filter'),
               url(r'^view/(?P<modelName>[\w]+)/(?P<modelPK>[\d]+)$', views.getViewSingleModelPage, {}, 'search_map_single_object'),
               #url(r'^view/(?P<modelName>[\w]+)/(?P<modelPK>[\d]+)$', views.getViewMultiModelPage, {}, 'search_map_single_object'),

               # replay in map page
               url(r'^replay/(?P<flight_name>[\w]+)$', views.getFlightPlaybackPage, {}, 'map_replay_flight'),
               url(r'^greplay/(?P<group_flight_name>[\w]+)$', views.getGroupFlightPlaybackPage, {}, 'map_replay_group_flight'),

               # Export datatable rows from search pages to CSV file
               url(r'^search/exportSearchResults/', views.ExportOrderListJson.as_view(), {}, 'exportSearchResults'),

               # Including these in this order ensures that reverse will return the non-rest urls for use in our server
               url(r'^rest/', include('xgds_map_server.restUrls')),
               url('', include('xgds_map_server.restUrls')),
               ]

xgds_map_server/forms.py
#__BEGIN_LICENSE__
# Copyright (c) 2015, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All rights reserved.
#
# The xGDS platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#__END_LICENSE__

import traceback
import datetime
import pytz

from django import forms
from django.conf import settings
from django.core.urlresolvers import reverse
from django.forms.fields import IntegerField, ChoiceField
from django.db.models import Q
from django.contrib.sites.models import Site

from resumable.fields import ResumableFileField

from xgds_map_server.models import KmlMap, MapGroup, MapLayer, MapTile,  MapDataTile, WMSTile, GeoJSON, Place, Geotiff
from geocamUtil.models import SiteFrame
from xgds_map_server.uploadGeotiff import upload_geotiff
# pylint: disable=C1001


def buildQueryForPlace(fieldname, field, value, hierarchy):
    """
    Build a query for place which handles hierarchy
    :param fieldname:
    :param field:
    :param value:
    :param hierarchy:
    :return:
    """
    if not value:
        return None

    if hierarchy:
        place_qs = Place.get_tree(value)
        return Q(**{fieldname + '__in': place_qs})
    else:
        return Q(**{fieldname+'__id': value.pk})


class AbstractMapForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=MapGroup.objects.filter(deleted=False), empty_label=None, label="Folder")
    username = forms.CharField(required=False, widget=forms.HiddenInput())
    region = forms.ModelChoiceField(queryset=SiteFrame.objects.all(), initial=settings.XGDS_CURRENT_SITEFRAME_ID, label=settings.XGDS_MAP_SERVER_SITE_MONIKER)
    
    def getModel(self):
        return None

    @staticmethod
    def getExclude():
        return ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'minLat', 'minLon', 'maxLat', 'maxLon']

    def getParentGroup(self):
        mapGroupName = self.cleaned_data['parent']
        foundParents = MapGroup.objects.filter(name=mapGroupName)
        return foundParents[0]

    class Meta:
        abstract = True
#         model = self.getModel()
        widgets = {
            # Note: no practical way to retrieve max lengths from Map model
            'name': forms.TextInput(attrs={'size': 50}),
            'description': forms.Textarea(attrs={'cols': 50, 'rows': 7})
        }
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'minLat', 'minLon', 'maxLat',
                   'maxLon']


class MapForm(AbstractMapForm):
    class Meta(AbstractMapForm.Meta):
        model = KmlMap


class MapGroupForm(AbstractMapForm):
    class Meta(AbstractMapForm.Meta):
        model = MapGroup


class MapLayerForm(AbstractMapForm):
    class Meta(AbstractMapForm.Meta):
        model = MapLayer
        exclude = ['minLat', 'minLon', 'maxLat', 'maxLon', 'jsonFeatures', 'creator', 'modifier', 'creation_time',
                   'modification_time', 'deleted', 'defaultColor']


class WMSTileForm(AbstractMapForm):
    def save(self, commit=True):
        instance = super(WMSTileForm, self).save(commit=False)
        if not instance.creator:
            instance.creator = self.cleaned_data['username']
            instance.creation_time = datetime.datetime.now(pytz.utc)
        else:
            instance.modifier = self.cleaned_data['username']
            instance.modification_time = self.cleaned_data['username']
        instance.parent = self.getParentGroup()
        if commit:
            instance.save()

    class Meta(AbstractMapForm.Meta):
        model = WMSTile
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'minLat', 'minLon', 'maxLat',
                   'maxLon']


class GeotiffForm(AbstractMapForm):
    sourceFile = ResumableFileField(
        allowed_mimes=("image/tiff",),
        upload_url=lambda: reverse('uploadResumable'),
        chunks_dir=getattr(settings, 'FILE_UPLOAD_TEMP_DIR'),
        label="GeoTiff File",
    )

    def save(self, commit=True):
        instance = super(GeotiffForm, self).save(commit=False)
        if not instance.creator:
            instance.creator = self.cleaned_data['username']
            instance.creation_time = datetime.datetime.now(pytz.utc)
        else:
            instance.modifier = self.cleaned_data['username']
            instance.modification_time = self.cleaned_data['username']
        instance.parent = self.getParentGroup()

        try:
            upload_geotiff(instance)
        except AssertionError as e:
            # TODO: properly handle an assertion error by returing a form error
            traceback.print_exc()
            return

        if commit:
            instance.save()

    class Meta(AbstractMapForm.Meta):
        model = Geotiff
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'minLat', 'minLon', 'maxLat', 'maxLon',
            'tileWidth', 'tileHeight', 'projectionName', 'wmsUrl', 'layers', 'wmsVersion', 'minLevel', 'maxLevel', 'srs', 'format', 'colorPalette']


class GeoJSONForm(AbstractMapForm):
    class Meta(AbstractMapForm.Meta):
        model = GeoJSON
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'minLat', 'minLon', 'maxLat', 'maxLon']


class MapLayerFromSelectedForm(AbstractMapForm):
    jsonFeatures = forms.CharField(widget=forms.HiddenInput())

    class Meta(AbstractMapForm.Meta):
        model = MapLayer
        exclude = ['minLat', 'minLon', 'maxLat', 'maxLon', 'creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'defaultColor']


class MapTileForm(AbstractMapForm):
    if settings.XGDS_MAP_SERVER_GDAL2TILES_ZOOM_LEVELS:
        minZoom = IntegerField(initial=12, label="Min Zoom")
        maxZoom = IntegerField(initial=20, label="Max Zoom", help_text="(UAV=23, Satellite=20)")
    
    resampleMethod = ChoiceField(choices=settings.XGDS_MAP_SERVER_GDAL_RESAMPLE_OPTIONS,
                                 label="Resampling")

    sourceFile = ResumableFileField(allowed_mimes=("image/tiff",),
                                    upload_url=lambda: reverse('uploadResumable'),
                                    chunks_dir=getattr(settings, 'FILE_UPLOAD_TEMP_DIR'),
                                    label="GeoTiff File"
                                    )

    def save(self, commit=True):
        instance = super(MapTileForm, self).save(commit=False)
        if not instance.creator:
            instance.creator = self.cleaned_data['username']
            instance.creation_time = datetime.datetime.now(pytz.utc)
        else:
            instance.modifier = self.cleaned_data['username']
            instance.modification_time = self.cleaned_data['username']
        instance.parent = self.getParentGroup()
        if commit:
            instance.save()

    class Meta(AbstractMapForm.Meta):
        model = MapTile
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'processed', 'minx', 'miny', 'maxx', 'maxy', 'resolutions', 'minLat', 'minLon', 'maxLat', 'maxLon']


class MapDataTileForm(MapTileForm):
    dataFile = ResumableFileField(allowed_mimes=("image/png",),
                                  upload_url=lambda: reverse('uploadResumable'),
                                  chunks_dir=getattr(settings, 'FILE_UPLOAD_TEMP_DIR'),
                                  label="Data File (png)"
                                  )
    
    legendFile = ResumableFileField(allowed_mimes=("image/png",),
                                  upload_url=lambda: reverse('uploadResumable'),
                                  chunks_dir=getattr(settings, 'FILE_UPLOAD_TEMP_DIR'),
                                  label="Legend File (png, vertical)"
                                  )
    
    class Meta(AbstractMapForm.Meta):
        model = MapDataTile
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'processed', 'minx', 'miny', 'maxx', 'maxy', 'resolutions']


class EditMapTileForm(AbstractMapForm):
    class Meta(AbstractMapForm.Meta):
        model = MapTile
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'processed', 'sourceFile', 'minx', 'miny', 'maxx', 'maxy', 'resolutions']



class EditGeotiffForm(AbstractMapForm):
    class Meta(AbstractMapForm.Meta):
        model = Geotiff
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'minLat', 'minLon', 'maxLat', 'maxLon',
            'tileWidth', 'tileHeight', 'projectionName', 'wmsUrl', 'layers', 'wmsVersion', 'minLevel', 'maxLevel', 'srs', 'format', 'colorPalette', 'sourceFile']



class EditMapDataTileForm(EditMapTileForm):
    class Meta(AbstractMapForm.Meta):
        model = MapDataTile
        exclude = ['creator', 'modifier', 'creation_time', 'modification_time', 'deleted', 'processed', 'sourceFile', 'minx', 'miny', 'maxx', 'maxy', 'resolutions']


class CollectionModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name


# class MapCollectionForm(AbstractMapForm):
#     collection = CollectionModelChoiceField(queryset=Collection.objects.all().order_by('name'), empty_label=None)
#
#     class Meta(AbstractMapForm.Meta):
#         model = MapCollection
#
#
# class MapSearchForm(AbstractMapForm):
#
#     class Meta(AbstractMapForm.Meta):
#         model = MapSearch

xgds_map_server/templates/AddDataTile.html
{% extends "MapBase.html" %}
{% load static %}

{% block cssExtras %}
<style scoped>
input[type='file'] {
  color: transparent;
}</style>
{% endblock cssExtras %}

{% block contents %}
{{ block.super }}
<div class="btn-toolbar" role="toolbar" >
  {% include "AddNodeButtons.html" %}
 </div>

{% if error %}<h4 style="color:red">Error: {{ errorText }}</h4>{% endif %}
<div >
<form action="#" enctype="multipart/form-data" method="post">
 <p>
<label></label>
<span class="h6">{{ title }}</span>
</p>
 <p>
 <label></label>
<span>{{instructions|safe }}</span>
</p>

{{ form.as_p }}

<p>
<label for="alert_span"></label>
<span class="alert alert-danger" role="alert" id="alert_span">
<strong>You cannot click the Create button until your upload finishes.</strong><br/>
After the processing completes, you should get an email with the results.
</span>
</p>
<p class="form-group">
<label for="create_button"></label>
<input type="submit" value="Create" id="create_button" disabled="disabled"/>
</p>
{% csrf_token %}

</form>
</div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src='{{ EXTERNAL_URL }}resumablejs/resumable.js'></script>
    <script type="text/javascript" src="{% static 'resumable/js/django-resumable.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'resumable/js/init.js' %}"></script> -->
{% endblock scripts %}

{% block jsInit %}
document.addEventListener("DOMContentLoaded", function () {
    "use strict";
    var dj;
    var numFiles = 0;
    if (new Resumable().support) {
    		var sourceFileEl = $('input#id_sourceFile');
		sourceFileEl.attr('data-upload-url', '/xgds_map_server/uploadResumable/');
		
		var dataFileEl = $('input#id_dataFile');
		dataFileEl.attr('data-upload-url', '/xgds_map_server/uploadResumable/');
		
		var legendFileEl = $('input#id_legendFile');
		legendFileEl.attr('data-upload-url', '/xgds_map_server/uploadResumable/');
		
        dj = new DjangoResumable({
        'onFileSuccess':function (r, file, message, el, progress, filePath, fileName) {
	    		"use strict";
	    		filePath.setAttribute('value', file.size + '_' + file.fileName);
	    		if (fileName !== null){
	    			fileName.innerHTML = file.fileName;
	    		} else {
	    			var sib = $(el).siblings('.helptext'); //sourceFileEl.siblings('.helptext');
	    			sib.html(file.fileName);
	    		}
	    		progress.style.display = 'none';
	    		if (!el.id.includes('legend')){
	    			numFiles++;
	    		}
	    		if (numFiles >= 2){
		    		$("#create_button").removeAttr("disabled");
		    	}
			}
		});
		dj.initField(sourceFileEl[0]);
		dj.initField(dataFileEl[0]);
		dj.initField(legendFileEl[0]);
    }
});
{% endblock jsInit %}

  {% block footer %}
  {% endblock footer %}

xgds_map_server/templates/AddLayer.html
{% extends "MapBase.html" %}

{% block contents %}
{{ block.super }}
<div class="btn-toolbar" role="toolbar" >
  {% include "AddNodeButtons.html" %}
 </div>

{% if error %}<h4 style="color:red">Error: {{ errorText }}</h4>{% endif %}
<form action="#" enctype="multipart/form-data" method="post">{% csrf_token %}
<p>
<label></label>
<span class="h6"> Add Map Layer</span>
</p>
<p>
<label></label>
<span>
Create a new Map Layer. You can add polygons, lines and points to the 
Map Layer in the Map Layer editor.
</span>
</p> 

{{ layerForm.as_p }}
<p class="form-group">
<label></label>
<input type="submit" value="Create" />
</p>
</form>
{% endblock %}

{% block footer %}
{% endblock footer %}

xgds_map_server/templates/AddMap.html
{% extends "MapBase.html" %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}xgds_map_server/js/MapForm.js" type="text/javascript"></script>
{% endblock %}

{% block contents %}
{{ block.super }}
<h3>Add Map</h3>
<form action="#" enctype="multipart/form-data" method="post">{% csrf_token %}
{% include "MapForm.html" %}
<input type="submit" value="Create" /><input type="button" onclick="document.location.href = '{{ mapTreeUrl }}'" value="Back" />
</form>
{% endblock %}

xgds_map_server/templates/AddMapSearch.html
{% extends "MapBase.html" %}

{% block contents %}
{{ block.super }}
{% if error %}<h4 style="color:red">Error: {{ errorText }}</h4>{% endif %}
<p>
<label></label>
<span class="h6"> Add Map Search</span>
</p><p>
Create a new map search -- a search for objects that can be turned on and off on the map.
</p> 
<form action="#" enctype="multipart/form-data" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create" />
</form>
{% endblock %}

xgds_map_server/templates/AddNode.html
{% extends "MapBase.html" %}

{% block contents %}
{{ block.super }}
 <div class="btn-toolbar" role="toolbar" >
  {% include "AddNodeButtons.html" %}
 </div>

{% if error %}<h4 style="color:red">Error: {{ errorText }}</h4>{% endif %}

<div class="mw-50">
<form action="#" enctype="multipart/form-data" method="post">{% csrf_token %}
    <p>
<label></label>
<span class="h6">{{ title }}</span>
</p>
<p>
{{ instruction }}
</p>
{{ form.as_p }}
<p class="form-group">
<label for="create_button"></label>
<input type="submit" value="Create" id="create_button" />
</p>
</form>
</div>
{% endblock %}

  {% block footer %}
  {% endblock footer %}

xgds_map_server/templates/DeletedNodes.html
{% extends "MapBase.html" %}
{% load get_class_name from utils %}

{% block contents %}
<h6>Deleted Elements</h6>
<p>Click an element to undelete it.</p>
<table class="table-striped">
{% for node in nodes %}
<tr>
<td>
{% if node|get_class_name == 'MapGroup' %}
<a href="{% url 'folderDelete' node.uuid %}">{{ node.name }}</a><br>
{% else %}
<a href="{% url 'nodeDelete' node.uuid %}">{{ node.name }}</a><br>
{% endif %}
</td>
</tr>
{% endfor %}
</table>
{% endblock %}

xgds_map_server/templates/EditMapTile.html
{% extends "MapBase.html" %}

{% block contents %}
{{ block.super }}
{% if error %}<h4 style="color:red">Error: {{ errorText }}</h4>{% endif %}
<h2>Edit Map Tile</h2>
<form action="#" enctype="multipart/form-data" method="post">{% csrf_token %}
{{ mapTileForm.as_p }}
<input type="submit" value="Save" />
</form>
{% endblock %}

{% block jsInit %}
{{ block.super }}
{% if fromSave %}
$(document).ready(function(){setTimeout(function(){$("#saveButton")[0].value="Save";},1500);});
{% endif %}
{% endblock %}

xgds_map_server/templates/MapBase.html
{% extends "base.html" %}
{% load nav %}
{% block siteSection %}Maps{% endblock %}
{% block sitemenu-content-secondary %}
{% include "map_subnav.html" %}
{% endblock %}

xgds_map_server/templates/MapForm.html
<!--<form action="http://some.url/" enctype="multipart/form-data" method="post">-->
<!--requires a variable called "mapForm"-->
{% if mapForm.non_field_errors %}<div class="alert alert-danger" role="alert">{{ mapForm.non_field_errors }}</div>{% endif %}
{% if mapForm.name.errors %}<div class="alert alert-danger" role="alert">{{ mapForm.name.errors }}</div>{% endif %}

<p>
<label></label>
<span>
The files you specify here will be available in the planner as a layer and in Google Earth via a map feed.
</span>
</p>
<p>
<label for="type_warning"></label>
<span class="alert alert-danger" role="alert" id="type_warning">
WARNING: Right now we do not support kmz files, nor do we support ground overlay in kml.<br/>
</span>
</p>
<p>
<label for="id_name">Map Name:</label> {{ mapForm.name }}<br/>
{% if mapForm.description.errors %}<span style="color:red">{{ mapForm.description.errors }}</span>{% endif %}
</p>
<p>
<label for="id_description">Description:</label> {{ mapForm.description }}<br>
</p>
<p>
{% if mapForm.openable.errors %}<span style="color:red">{{ mapForm.openable.errors }}</span>{% endif %}
<label for="id_openable">Openable:</label> {{ mapForm.openable }}<br/>
</p>
<p class="form-group">
{% if mapForm.visible.errors %}<span style="color:red">{{ mapForm.visible.errors }}</span>{% endif %}
	<label for="id_visible">Visible:</label>
	<span class="form-check">
		<input id="id_visible" name="visible" type="checkbox"> 
		<span style="width:300px;" class="ml-3">
			Check to turn ON by default.
		</span>
	</span>
</p>
<p>
{% if mapForm.transparency.errors %}<span style="color:red">{{ mapForm.transparency.errors }}</span>{% endif %}
<label for="id_transparency">Transparency:</label> {{ mapForm.transparency }}<span class="helptext">(100=transparent)</span><br/>
</p>
<p>
{% if mapForm.parentId.errors %}<span style="color:red">{{ mapForm.parentId.errors }}</span>{% endif %}
<label for="id_parent">In Folder:</label> {{ mapForm.parent }}<br/>
</p>
<p>
{% if mapForm.region.errors %}<span style="color:red">{{ mapForm.region.errors }}</span>{% endif %}
<label for="id_region">Region:</label> {{ mapForm.region }}<br/>
</p>
<p>
	<label >Type:</label>
	<span class="btn-group" role="group" data-toggle="buttons">
		<label class="btn btn-primary {% if not kmlChecked %} active {% endif %}"> 
			<input type="radio" value="file" name="typeChooser"
			{% if not kmlChecked %} checked {% endif %} id="typeChooser"></input>
			File Upload
		</label>
		<label class="btn btn-primary {% if kmlChecked %} active {% endif %}"> 
			<input type="radio" value="kml" name="typeChooser"
			{% if kmlChecked %}checked{% endif %} id="typeChooser"></input> KML
			Url
		</label>
	</span>
</p>
<p id="kmlFile_div" >
{% if mapForm.kmlFile.errors %}<span style="color:red">{{ mapForm.kmlFile.errors }}</span>{% endif %}
<label for="id_kmlFile" class="col-form-label col-sm-2 d-flex justify-content-end">KML URL:</label> 
<input id="id_kmlFile" maxlength="200" name="kmlFile" type="text" style="width:300px;">
</p>
<p id="localFile_div" >
{% if mapForm.localFile.errors %}<span style="color:red">{{ mapForm.localFile.errors }}</span>{% endif %}
<label for="id_localFile" class="col-form-label col-sm-2 d-flex justify-content-end">Upload File:</label> 
<input id="id_localFile" name="localFile" type="file" style="width:300px;">
</p>


{% block footer %}
{% endblock footer %}